### ISSUE TITLE
Team Section

### ISSUE THREAD

**Issue by yassineuuu** [Hypernova-II/Hypernova-Agency#12]
Code the Team section "responsive" on the 3 platforms : 

- [x] Desktop 

- [x] Tablet 

- [x] Mobile

**Comment by umeima** [comment]
le problème est résolu

**Comment by umeima** [comment]
j'ai terminé le code de la partie team et maintenant je l'ai pushé pour la révision

**Comment by M-Marou** [comment]
nice work
