### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by yassineuuu** [Hypernova-II/Hypernova-Agency#14]
Code the Footer section "responsive" on the 3 platforms : 

- [x] Desktop 

- [x] Tablet 

- [x] Mobile

**Comment by M-Marou** [comment]
footer mobile & tablet responsive up for review!

**Comment by M-Marou** [comment]
done footer section, now fully responsive on the 3 platforms, up for review!

**Comment by yassineuuu** [comment]
Nice, good joob let's keep this spirit
