### ISSUE TITLE
Veille : SASS

### ISSUE THREAD

**Issue by M-Marou** [Hypernova-II/Hypernova-Agency#8]
Veille in SASS.

**Comment by M-Marou** [comment]
Veille was good!

**Comment by yassineuuu** [comment]
the" veille" was very helpful

**Comment by meach-kaddour** [comment]
oui, je pense qu'on a besoin d'autres .

**Comment by omayma96** [comment]
veille est bien passé , on a appris beaucoup de chose pour qu'on puisse améliorer notre travail avec SASS

**Comment by umeima** [comment]
on a appris beaucoup de chose sur le SASS pour le moment j'ai seulement des petites difficultés avec nesting
